#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_DIR"

if [[ -f "$PROJECT_DIR/.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "$PROJECT_DIR/.env"
  set +a
fi

export PYTHONPATH="$PROJECT_DIR/src${PYTHONPATH:+:${PYTHONPATH}}"
export CLAWBOT_POLICY_FILE="${CLAWBOT_POLICY_FILE:-$PROJECT_DIR/config/policy.yaml}"
export CLAWBOT_DB_PATH="${CLAWBOT_DB_PATH:-$PROJECT_DIR/data/clawbot.db}"
export CLAWBOT_MEDIA_ROOT="${CLAWBOT_MEDIA_ROOT:-$PROJECT_DIR/data/media}"
export CLAWBOT_EXPORT_ROOT="${CLAWBOT_EXPORT_ROOT:-$PROJECT_DIR/data/exports}"

# OpenClaw + an LLM is the primary production path. Policy mode is an explicit fallback.
export CLAWBOT_DECISION_MODE="${CLAWBOT_DECISION_MODE:-agent}"
export CLAWBOT_OPENCLAW_BIN="${CLAWBOT_OPENCLAW_BIN:-openclaw}"
export CLAWBOT_OPENCLAW_AGENT_ID="${CLAWBOT_OPENCLAW_AGENT_ID:-kefu_ops}"
export CLAWBOT_OPENCLAW_TIMEOUT_SEC="${CLAWBOT_OPENCLAW_TIMEOUT_SEC:-120}"
export CLAWBOT_OPENCLAW_LOCAL="${CLAWBOT_OPENCLAW_LOCAL:-1}"

PORT="${CLAWBOT_PORT:-18080}"
HOST="${CLAWBOT_HOST:-127.0.0.1}"
DEFAULT_PY_BIN="python3"
if [[ -x "${PROJECT_DIR}/.venv/bin/python" ]]; then
  DEFAULT_PY_BIN="${PROJECT_DIR}/.venv/bin/python"
fi
PY_BIN="${CLAWBOT_PYTHON_BIN:-${DEFAULT_PY_BIN}}"

export CLAWBOT_TOOL_BASE_URL="${CLAWBOT_TOOL_BASE_URL:-http://127.0.0.1:${PORT}}"
export CLAWBOT_TOOL_API_KEY="${CLAWBOT_TOOL_API_KEY:-}"
export CLAWBOT_TOOL_TIMEOUT_SEC="${CLAWBOT_TOOL_TIMEOUT_SEC:-8}"
export CLAWBOT_ENABLE_ADMIN_QUERY_TOOLS="${CLAWBOT_ENABLE_ADMIN_QUERY_TOOLS:-0}"
export CLAWBOT_ENABLE_REFUND_WRITE_TOOL="${CLAWBOT_ENABLE_REFUND_WRITE_TOOL:-0}"
export CLAWBOT_ENABLE_BLACKLIST_WRITE_TOOLS="${CLAWBOT_ENABLE_BLACKLIST_WRITE_TOOLS:-0}"
export CLAWBOT_ENABLE_OFFLINE_ADMIN_TOOLS="${CLAWBOT_ENABLE_OFFLINE_ADMIN_TOOLS:-0}"
export CLAWBOT_ENABLE_IMAGE_INSPECT_TOOL="${CLAWBOT_ENABLE_IMAGE_INSPECT_TOOL:-0}"
export CLAWBOT_ENABLE_FILE_READ_TOOL="${CLAWBOT_ENABLE_FILE_READ_TOOL:-0}"
export CLAWBOT_ENABLE_SHELL_EXEC_TOOL="${CLAWBOT_ENABLE_SHELL_EXEC_TOOL:-0}"
export CLAWBOT_ENABLE_OPENCLAW_BUILTINS="${CLAWBOT_ENABLE_OPENCLAW_BUILTINS:-0}"
export CLAWBOT_TARGET_OUTER_ID="${CLAWBOT_TARGET_OUTER_ID:-}"
export CLAWBOT_IDENTITY_BASE_URL="${CLAWBOT_IDENTITY_BASE_URL:-}"
export CLAWBOT_IDENTITY_ORG_ID="${CLAWBOT_IDENTITY_ORG_ID:-}"
export CLAWBOT_IDENTITY_ROOM_NAME="${CLAWBOT_IDENTITY_ROOM_NAME:-}"
export CLAWBOT_IDENTITY_API_KEY="${CLAWBOT_IDENTITY_API_KEY:-}"

export CLAWBOT_KUAIMAI_ERP_HOST="${CLAWBOT_KUAIMAI_ERP_HOST:-https://erp.superboss.cc}"
export CLAWBOT_KUAIMAI_COMPANY_NAME="${CLAWBOT_KUAIMAI_COMPANY_NAME:-}"
export CLAWBOT_KUAIMAI_ACCOUNT="${CLAWBOT_KUAIMAI_ACCOUNT:-}"
export CLAWBOT_KUAIMAI_PASSWORD="${CLAWBOT_KUAIMAI_PASSWORD:-}"
export CLAWBOT_KUAIMAI_COMPANY_ID="${CLAWBOT_KUAIMAI_COMPANY_ID:-}"
export CLAWBOT_KUAIMAI_SNAPSHOT_TTL_SEC="${CLAWBOT_KUAIMAI_SNAPSHOT_TTL_SEC:-300}"
export CLAWBOT_KUAIMAI_STORAGE_STATE="${CLAWBOT_KUAIMAI_STORAGE_STATE:-$PROJECT_DIR/data/kuaimai_storage_state.json}"
export CLAWBOT_KUAIMAI_LOGIN_HEADLESS="${CLAWBOT_KUAIMAI_LOGIN_HEADLESS:-1}"
export CLAWBOT_KUAIMAI_CHROMIUM_PATH="${CLAWBOT_KUAIMAI_CHROMIUM_PATH:-}"
export CLAWBOT_KUAIMAI_BROWSER_CHANNEL="${CLAWBOT_KUAIMAI_BROWSER_CHANNEL:-chrome}"

export CLAWBOT_VISION_PROVIDER="${CLAWBOT_VISION_PROVIDER:-disabled}"
export CLAWBOT_IMAGE_INSPECT_ENABLED="${CLAWBOT_IMAGE_INSPECT_ENABLED:-0}"
export CLAWBOT_QWEN_VL_API_KEY="${CLAWBOT_QWEN_VL_API_KEY:-}"
export CLAWBOT_QWEN_VL_MODEL="${CLAWBOT_QWEN_VL_MODEL:-qwen3-vl-plus}"
export CLAWBOT_QWEN_VL_BASE_URL="${CLAWBOT_QWEN_VL_BASE_URL:-https://dashscope.aliyuncs.com/compatible-mode/v1}"
export CLAWBOT_VISION_TIMEOUT_SEC="${CLAWBOT_VISION_TIMEOUT_SEC:-20}"
export CLAWBOT_WORKER_OCR_PROVIDER="${CLAWBOT_WORKER_OCR_PROVIDER:-openclaw}"
export CLAWBOT_HERMES_OCR_URL="${CLAWBOT_HERMES_OCR_URL:-}"
export CLAWBOT_HERMES_OCR_ROUTE="${CLAWBOT_HERMES_OCR_ROUTE:-}"
export CLAWBOT_HERMES_OCR_MODEL="${CLAWBOT_HERMES_OCR_MODEL:-}"
export CLAWBOT_HERMES_OCR_API_KEY="${CLAWBOT_HERMES_OCR_API_KEY:-}"

export CLAWBOT_WECOM_ENABLED="${CLAWBOT_WECOM_ENABLED:-0}"
export CLAWBOT_WECOM_CORP_ID="${CLAWBOT_WECOM_CORP_ID:-}"
export CLAWBOT_WECOM_AGENT_ID="${CLAWBOT_WECOM_AGENT_ID:-}"
export CLAWBOT_WECOM_APP_SECRET="${CLAWBOT_WECOM_APP_SECRET:-}"
export CLAWBOT_WECOM_TOKEN="${CLAWBOT_WECOM_TOKEN:-}"
export CLAWBOT_WECOM_AES_KEY="${CLAWBOT_WECOM_AES_KEY:-}"
export CLAWBOT_WECOM_APP_NAME="${CLAWBOT_WECOM_APP_NAME:-clawbot}"
export CLAWBOT_WECOM_HUB_URL="${CLAWBOT_WECOM_HUB_URL:-}"
export CLAWBOT_WECOM_HUB_API_KEY="${CLAWBOT_WECOM_HUB_API_KEY:-}"
export CLAWBOT_WECOM_APP_KEY="${CLAWBOT_WECOM_APP_KEY:-${CLAWBOT_OPENCLAW_AGENT_ID}}"

export CLAWBOT_ADB_CAPTURE_ENABLED="${CLAWBOT_ADB_CAPTURE_ENABLED:-0}"
export CLAWBOT_ADB_BIN="${CLAWBOT_ADB_BIN:-adb}"
export CLAWBOT_ADB_CAPTURE_TIMEOUT_SEC="${CLAWBOT_ADB_CAPTURE_TIMEOUT_SEC:-5}"

if [[ "$CLAWBOT_DECISION_MODE" == "agent" ]] && ! command -v "$CLAWBOT_OPENCLAW_BIN" >/dev/null 2>&1; then
  echo "ERROR: OpenClaw executable not found: $CLAWBOT_OPENCLAW_BIN" >&2
  echo "Install/configure OpenClaw, or set CLAWBOT_DECISION_MODE=policy for fallback mode." >&2
  exit 1
fi

exec "$PY_BIN" -m uvicorn kefu_clawbot.main:app --host "$HOST" --port "$PORT"
